import type { RegionId } from "./types";

export const regionMeta: Record<RegionId, { name: string; color: string }> = {
  moscow: { name: "Московская область", color: "#245eb7" }, tver: { name: "Тверская область", color: "#327a76" }, vladimir: { name: "Владимирская область", color: "#8c5d9e" }, kaluga: { name: "Калужская область", color: "#aa6c3b" }, tula: { name: "Тульская область", color: "#ad4e53" }, ryazan: { name: "Рязанская область", color: "#387a9b" }, yaroslavl: { name: "Ярославская область", color: "#6c7d35" }, smolensk: { name: "Смоленская область", color: "#4f7598" }, kostroma: { name: "Костромская область", color: "#8a7045" }, ivanovo: { name: "Ивановская область", color: "#5a719a" }, nizhny: { name: "Нижегородская область", color: "#9a5f45" }, vologda: { name: "Вологодская область", color: "#4e8696" }, bryansk: { name: "Брянская область", color: "#9a6942" }, oryol: { name: "Орловская область", color: "#857443" }, lipetsk: { name: "Липецкая область", color: "#a65f53" }, tambov: { name: "Тамбовская область", color: "#5c7d5c" }, mordovia: { name: "Республика Мордовия", color: "#a9697e" }, chuvashia: { name: "Чувашская Республика", color: "#5077a5" },
};

export const regionSources: { path: string; region: RegionId }[] = [
  { path: "/data/moscow-oblast-municipalities.json", region: "moscow" }, { path: "/data/tver-oblast-municipalities.json", region: "tver" }, { path: "/data/vladimir-oblast-municipalities.json", region: "vladimir" }, { path: "/data/kaluga-oblast-municipalities.json", region: "kaluga" }, { path: "/data/tula-oblast-municipalities.json", region: "tula" }, { path: "/data/ryazan-oblast-municipalities.json", region: "ryazan" }, { path: "/data/yaroslavl-oblast-municipalities.json", region: "yaroslavl" }, { path: "/data/smolensk-oblast-municipalities.json", region: "smolensk" }, { path: "/data/kostroma-oblast-municipalities.json", region: "kostroma" }, { path: "/data/ivanovo-oblast-municipalities.json", region: "ivanovo" }, { path: "/data/nizhny-novgorod-oblast-municipalities.json", region: "nizhny" }, { path: "/data/vologda-oblast-municipalities.json", region: "vologda" }, { path: "/data/bryansk-oblast-municipalities.json", region: "bryansk" }, { path: "/data/oryol-oblast-municipalities.json", region: "oryol" }, { path: "/data/lipetsk-oblast-municipalities.json", region: "lipetsk" }, { path: "/data/tambov-oblast-municipalities.json", region: "tambov" }, { path: "/data/mordovia-municipalities.json", region: "mordovia" }, { path: "/data/chuvashia-municipalities.json", region: "chuvashia" },
];
